### ISSUE TITLE
New update broke the focused feed bar background

### ISSUE THREAD

**Issue by ahloiscreamo** [aleck07/youtube#9]
Hello,
as the title

![Image](https://github.com/user-attachments/assets/19e1643b-c32c-4044-bda3-05712655de2e)

**Comment by justintfranklin** [comment]
Adding this CSS should fix it.
```css
yt-chip-cloud-chip-renderer[chip-style=STYLE_DEFAULT][selected] #chip-container.yt-chip-cloud-chip-renderer, 
yt-chip-cloud-chip-renderer[chip-style=STYLE_HOME_FILTER][selected] #chip-container.yt-chip-cloud-chip-renderer
{
    background-color: var(--main-color) !important;
}
```
